using Haruka.Arcade.SegaAMFileLib.AMDaemon.V1.DLI;
using Haruka.Arcade.SegaAMFileLib.AMDaemon.V1.ICF;
using Haruka.Arcade.SegaAMFileLib.CryptHash;
using Microsoft.Extensions.Logging;

namespace Haruka.Arcade.SegaAMFileCmd.Modules.DLIWrite {
    class DLIWriteRunner {
        internal static int Run(Options opts) {
            Program.SetGlobalOptions(opts);

            List<string> exist = new List<string>();

            if (opts.BaseIcfFileName != null) {
                if (!File.Exists(opts.BaseIcfFileName)) {
                    Program.CmdLog.LogError("Specified file not found: {f}", opts.BaseIcfFileName);
                    return 1;
                }

                EncryptionEnvironment.Initialize(opts.KeyFile);

                InstallationConfigurationFile icf = new InstallationConfigurationFile(File.ReadAllBytes(opts.BaseIcfFileName), EncryptionEnvironment.Icf, opts.IgnoreCrc);
                exist.Add(icf.GetSystemRecord()?.GetFileName(icf.Header) ?? throw new IOException("ICF file invalid: no system record exists"));

                if (!opts.IcfSystemOnly) {
                    exist.Add(icf.GetAppRecord()?.GetFileName(icf.Header) ?? throw new IOException("ICF file invalid: no app record exists"));
                }
            }

            exist.AddRange(opts.Exists.ToArray());

            DownloadInstructionFile dli = new DownloadInstructionFile {
                Common = {
                    DlFormat = 5.00F,
                    GameId = opts.GameId,
                    ReleaseTime = opts.OrderTime ?? DateTime.Now,
                    OrderTime = opts.ReleaseTime ?? DateTime.Now,
                    PartSize = new uint[] { 1024, 2048, 8_388_608 },
                    IsdnDownloadInterval = new int[] { 1000, -1 },
                    AdslDownloadInterval = new int[] { 1000, -1 },
                    BroadbandDownloadInterval = new int[] { 1000, -1 },
                    CloudDownloadAllowed = new DownloadInstructionFile.CloudDownload[48],
                    ReportUrl = opts.ReportUrl ?? "http://0.0.0.0",
                    ReportInterval = 3600,
                    GameDescription = "Generated by SegaAMFileLib",
                    InstallUrls = opts.Urls.ToArray(),
                    ExistUrls = exist.ToArray(),
                    PrivateInstallUrls = new string[] { }
                }
            };

            dli.Common.DownloadId = DownloadIdCalculator.GetDownloadId(dli);
            if (opts.Type == DliType.Opt) {
                dli.Common.ReleaseType = OptReleaseType.Sequential;
            }

            Array.Fill(dli.Common.CloudDownloadAllowed, DownloadInstructionFile.CloudDownload.Allowed);

            string output = dli.Write(opts.Type);

            File.WriteAllText(opts.OutputFile, output);

            Program.CmdLog.LogInformation("DLI written to: {f}", opts.OutputFile);

            return 0;
        }
    }
}