using Haruka.Arcade.SegaAMFileLib.AMDaemon.V1;
using Haruka.Arcade.SegaAMFileLib.AMDaemon.V1.DLI;
using Haruka.Arcade.SegaAMFileLib.AMDaemon.V1.ICF;
using Haruka.Arcade.SegaAMFileLib.CryptHash;
using Microsoft.Extensions.Logging;
using Version = Haruka.Arcade.SegaAMFileLib.AMDaemon.V1.Version;

namespace Haruka.Arcade.SegaAMFileCmd.Modules.DLIWrite {
    class DLIWriteRunner {
        internal static int Run(Options opts) {
            Program.SetGlobalOptions(opts);

            DownloadInstructionFile dli = new DownloadInstructionFile(opts.Type);
            
            dli.Common.DlFormat = 5.00F;
            dli.Common.GameId = opts.GameId;
            dli.Common.ReleaseTime = opts.OrderTime ?? DateTime.Now;
            dli.Common.OrderTime = opts.ReleaseTime ?? DateTime.Now;
            dli.Common.PartSize = new uint[] { 1024, 2048, 4096 };
            dli.Common.IsdnDownloadInterval = new int[] { 1000, -1 };
            dli.Common.AdslDownloadInterval = new int[] { 1000, -1 };
            dli.Common.BroadbandDownloadInterval = new int[] { 1000, -1 };
            dli.Common.CloudDownloadAllowed = new DownloadInstructionFile.CloudDownload[48];
            Array.Fill(dli.Common.CloudDownloadAllowed, DownloadInstructionFile.CloudDownload.ALLOWED);
            dli.Common.ReportUrl = opts.ReportUrl ?? "http://0.0.0.0";
            dli.Common.ReportInterval = 3600;
            dli.Common.GameDescription = "Generated by SegaAMFileLib";
            if (opts.Type == DliType.Opt) {
                dli.Common.ReleaseType = OptReleaseType.Sequential;
            }
            dli.Common.InstallUrls = opts.Urls;
            dli.Common.ExistUrls = new string[] { };
            dli.Common.PrivateInstallUrls = new string[] { };
            dli.Common.DownloadId = DownloadIdCalculator.GetDownloadId(dli);
            string output = dli.Write(opts.Type);
            
            File.WriteAllText(opts.OutputFile, output);
            
            Program.Log.LogInformation("DLI written to: {f}", opts.OutputFile);
            
            return 0;
        }
    }
}