<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <Title>Sega AM File Library</Title>
        <Description>Allows reading and writing of common file formats used by Sega's Arcade systems</Description>
        <Copyright>2025-2026 Akechi Haruka</Copyright>
        <Company>Haruka Akechi</Company>
        <AssemblyVersion></AssemblyVersion>
        <RootNamespace>Haruka.Arcade.SegaAMFileLib</RootNamespace>
        <Version>0.3.0</Version>
        <PackageProjectUrl>https://github.com/akechi-haruka/SegaAMFileLib/</PackageProjectUrl>
        <RepositoryUrl>https://github.com/akechi-haruka/SegaAMFileLib/</RepositoryUrl>
        <PackageTags>Arcade;File Formats</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="LTRData.DiscUtils.ExFat" Version="1.0.82"/>
        <PackageReference Include="LTRData.DiscUtils.Ntfs" Version="1.0.82"/>
        <PackageReference Include="LTRData.DiscUtils.Vhd" Version="1.0.82"/>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.3" />
        <PackageReference Include="NReco.Logging.File" Version="1.3.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Haruka.Common\Haruka.Common.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="Haruka.Common.Settings.local.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    
    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
    </PropertyGroup>

</Project>
